"pretrained_model_path": "/content/FollowYourPose/checkpoints/stable-diffusion-v1-4"
"output_dir": "/content/inference_output/"
"validation_data":
  "prompts":
  - "Iron man on the beach"
  - "Stormtrooper on the sea"
  - "Astronaut on the beach"
  "video_length": !!int "8"
  "width": !!int "512"
  "height": !!int "512"
  "num_inference_steps": !!int "50"
  "guidance_scale": !!float "12.5"
  "use_inv_latent": !!bool "false"
  "num_inv_steps": !!int "50"
  "dataset_set": "val"
"train_batch_size": !!int "1"
"validation_steps": !!int "100"
"resume_from_checkpoint": "/content/FollowYourPose/checkpoints/followyourpose_checkpoint-1000"
"seed": !!int "33"
"mixed_precision": "no"
"gradient_checkpointing": !!bool "false"
"enable_xformers_memory_efficient_attention": !!bool "true"
